Homework 3
Sushentsev/Homework pull request #51
Opened 2018-03-10 22:08 UTC by Sushentsev

Задачи 1, 2, 3, но при тестировании первой задачи тесты не проходят из-за NullReferenceException, не могу понять, в чем проблема :(

2018-03-31 12:30 UTC, yurii-litvinov requested changes
Вторая и третья зачтены, в первой надо привести тесты в порядок.

2018-03-31 12:30 UTC, yurii-litvinov commented on semester_4/hw3/Task_1-4/Task_1-4.Tests/TasksTests.fs
> +            evenNumbersFold [1..100] |> should equal 50
Копипаст суть ересь. Посмотрите https://github.com/nunit/docs/wiki/TestCaseData

2018-03-31 12:30 UTC, yurii-litvinov commented on semester_4/hw3/Task_1-4/Task_1-4.Tests/TasksTests.fs
> +            evenNumbersFold [1..100] |> should equal 50
Кроме того, у меня ни один из этих тестов вообще не прошёл --- потому что evenNumbersFold и т.д. --- это значения, определённые в другом модуле, NUnit это почему-то сильно огорчает (они инициализируются null-ами). Если сделать их функциями, всё должно быть ок.

2018-03-31 12:30 UTC, yurii-litvinov commented on semester_4/hw3/Task_1-4/Task_1-4.Tests/TasksTests.fs
> +        map tree func |> should equal res
А для пустого (или вырожденного) дерева как обстоят дела?

2018-04-14 14:05 UTC, Sushentsev commented on semester_4/hw3/Task_1-4/Task_1-4.Tests/TasksTests.fs
> +            evenNumbersFold [1..100] |> should equal 50
Все, я разобрался, тесты для 1 задачи заработали, но так и остались проблемы с тестами для 4-ой

2018-04-30 08:41 UTC, yurii-litvinov requested changes
Чтобы тесты сами запускались из Visual Studio, надо ещё NUnit3TestAdapter поставить как NuGet-пакет. А для 4-й задачи тесты не проходят потому, что primeSeq --- это значение, определённое в другом модуле, код инициализации которого NUnit не вызывает (потому что не знает ничего про F#). Сделайте primeSeq функцией, возвращающей эту последовательность, должно помочь.

2018-04-30 08:41 UTC, yurii-litvinov commented on semester_4/hw3/Task_1-4/Task_1-4/Hw4.fs
> +﻿namespace Homework3
Файл называется Hw4.fs, подозрительно :)

2018-06-01 10:16 UTC, yurii-litvinov approved these changes
Всё ок, зачтена

2018-06-04 00:00 UTC, merged